package de.thm.mni.backend.ticket

import de.thm.mni.backend.mail.MailRepository
import org.springframework.stereotype.Service
import java.security.SecureRandom

/**
 * Manages support ticket numbers in subjects and persisted mail records.
 */
@Service
class SupportTicketService(private val mailRepository: MailRepository) {
    private val random = SecureRandom()

    /**
     * Reads an existing ticket number from a mail subject.
     *
     * @param subject Mail subject entered by a customer or generated by the application.
     * @return Ticket number in canonical uppercase form, or null when no ticket number exists.
     */
    fun extractTicketNumber(subject: String): String? {
        return TICKET_PATTERN.find(subject)?.groupValues?.get(1)?.uppercase()
    }

    /**
     * Builds the subject used when answering an imported support mail.
     *
     * @param originalSubject Subject of the incoming support mail.
     * @param ticketNumber Existing or newly generated ticket number.
     * @return Canonical reply subject with ticket number.
     */
    fun buildReplySubject(originalSubject: String, ticketNumber: String): String {
        return normalizeReplySubject(originalSubject, ticketNumber)
    }

    /**
     * Produces the canonical reply subject with exactly one ticket number and one reply prefix.
     *
     * @param subject Subject provided by the draft or reply flow.
     * @param ticketNumber Ticket number that must appear in the outgoing subject.
     * @return Canonical reply subject with exactly one ticket prefix.
     */
    fun prependTicketIfMissing(subject: String, ticketNumber: String): String {
        return normalizeReplySubject(subject, ticketNumber)
    }

    /**
     * Normalizes a subject line to include exactly one ticket number and one reply prefix.
     */
    private fun normalizeReplySubject(subject: String, ticketNumber: String): String {
        val subjectWithoutTickets = subject.replace(TICKET_REFERENCE_PATTERN, " ").trim()
        val baseSubject = subjectWithoutTickets
            .replace(LEADING_REPLY_PREFIXES_PATTERN, "")
            .trim()
            .ifBlank { DEFAULT_SUPPORT_SUBJECT }
        return "[$ticketNumber] $REPLY_PREFIX $baseSubject".trim()
    }

    /**
     * Generates a random ticket number that is not yet present in stored mails.
     *
     * @return Unique ticket number using the configured ticket format.
     */
    fun generateUniqueTicketNumber(): String {
        var ticketNumber: String
        do {
            val number = random.nextInt(TICKET_BOUND).toString().padStart(TICKET_DIGITS, '0')
            ticketNumber = "$TICKET_PREFIX$number"
        } while (mailRepository.existsByTicketNumber(ticketNumber))
        return ticketNumber
    }

    /**
     * Removes a ticket number prefix from a subject, if present.
     *
     * @param subject Subject that may contain a ticket number prefix.
     * @return Subject without the ticket prefix.
     */
    fun removeTicketPrefix(subject: String): String {
        return subject.replace(Regex("^\\s*\\[$TICKET_PREFIX\\d{$TICKET_DIGITS}]\\s*", RegexOption.IGNORE_CASE), "")
            .trim()
    }

    /**
     * Constants and regular expressions for canonical ticket subject handling.
     */
    private companion object {
        const val REPLY_PREFIX = "Re:"
        const val TICKET_PREFIX = "TICKET-"
        const val DEFAULT_SUPPORT_SUBJECT = "Support request"
        const val TICKET_DIGITS = 6
        const val TICKET_BOUND = 1_000_000
        val TICKET_PATTERN = Regex("\\b(TICKET-\\d{$TICKET_DIGITS})\\b", RegexOption.IGNORE_CASE)
        val TICKET_REFERENCE_PATTERN = Regex("\\[?\\s*TICKET-\\d{$TICKET_DIGITS}\\s*]?", RegexOption.IGNORE_CASE)
        val LEADING_REPLY_PREFIXES_PATTERN = Regex("^(?:\\s*Re\\s*:\\s*)+", RegexOption.IGNORE_CASE)
    }
}
