server {
    listen ${PORT};
    server_name ${SERVER_NAME};

    return 301 https://$host$request_uri;
}

server {
    # SSL configuration
    listen ${SSL_PORT} ssl;
    server_name ${SERVER_NAME};

    ssl_certificate     ${SSL_CERT_FILE};
    ssl_certificate_key ${SSL_CERT_KEY_FILE};

    ssl_protocols TLSv1.2 TLSv1.3;
    server_tokens off;

    # Security headers
    proxy_set_header Host              $host;
    proxy_set_header X-Real-IP         $remote_addr;
    proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Host  $host;
    proxy_set_header X-Forwarded-Port  443;
    proxy_set_header X-Forwarded-Proto https;


    client_max_body_size 25m;

    # configuration for the mail client and mail server
    location = / {
        return 301 /app/;
    }

    # Configuration for the mail client
    location /app/ {
        modsecurity off;
        proxy_pass http://mail-client:8080/app/;
        proxy_http_version 1.1;
    }

    # Configuration for the mail server
    location /api/ {
        proxy_pass http://mail-server:8080/api/;
        proxy_http_version 1.1;
    }

    location /realms/ {
        modsecurity off;
        proxy_pass http://keycloak:8080/realms/;
        proxy_http_version 1.1;
    }

    location /resources/ {
        modsecurity off;
        proxy_pass http://keycloak:8080/resources/;
        proxy_http_version 1.1;
    }

    location /admin/ {
        modsecurity off;
        proxy_pass http://keycloak:8080/admin/;
        proxy_http_version 1.1;
    }


    location = /healthz {
        access_log off;
        modsecurity off;
        default_type text/plain;
        return 200 "healthy\n";
    }
}
